# Generated by Django 5.2.10 on 2026-01-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
