# Generated by Django 5.2.10 on 2026-01-15 15:38

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text')),
            ],
            options={
                'verbose_name': 'Project Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('call_to_action', 12)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your heading', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'help_text': 'Select heading size'}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('portfolio.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 50, 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('title', 7), ('text', 8), ('button_page', 9), ('button_url', 10), ('button_text', 11)]], {})})),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='portfolio.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portfolio_homepage', serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Main title displayed in the hero section', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Subtitle or tagline', max_length=300)),
                ('hero_cta_text', models.CharField(blank=True, default='View My Work', max_length=50)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('call_to_action', 12), ('two_columns', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your heading', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'help_text': 'Select heading size'}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('portfolio.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 50, 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('title', 7), ('text', 8), ('button_page', 9), ('button_url', 10), ('button_text', 11)]], {}), 13: ('wagtail.blocks.RichTextBlock', (), {}), 14: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 13), ('image', 6)]], {'icon': 'arrow-left', 'label': 'Left column content'}), 15: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 13), ('image', 6)]], {'icon': 'arrow-right', 'label': 'Right column content'}), 16: ('wagtail.blocks.StructBlock', [[('left_column', 14), ('right_column', 15)]], {})})),
                ('hero_cta_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Homepage',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='Project Date')),
                ('intro', models.TextField(help_text='Brief project description', max_length=500)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('live_url', models.URLField(blank=True, help_text='Live project URL')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('call_to_action', 12), ('two_columns', 16)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your heading', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'help_text': 'Select heading size'}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('portfolio.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 50, 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('title', 7), ('text', 8), ('button_page', 9), ('button_url', 10), ('button_text', 11)]], {}), 13: ('wagtail.blocks.RichTextBlock', (), {}), 14: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 13), ('image', 6)]], {'icon': 'arrow-left', 'label': 'Left column content'}), 15: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 13), ('image', 6)]], {'icon': 'arrow-right', 'label': 'Right column content'}), 16: ('wagtail.blocks.StructBlock', [[('left_column', 14), ('right_column', 15)]], {})})),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('technologies', models.ManyToManyField(blank=True, help_text='Select technologies used in this project', to='portfolio.technology')),
            ],
            options={
                'verbose_name': 'Project Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
