# Generated by Django 5.2.10 on 2026-01-15 17:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Over Pagina'},
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Pagina'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Pagina'},
        ),
        migrations.AlterModelOptions(
            name='projectindexpage',
            options={'verbose_name': 'Project Index Pagina'},
        ),
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name': 'Project Pagina'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['name'], 'verbose_name_plural': 'Technologieën'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_projects_title',
            field=models.CharField(default='Uitgelichte projecten', help_text='Titel voor de uitgelichte projecten sectie', max_length=100, verbose_name='Projecten titel'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Korte introductie tekst', verbose_name='Introductie'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 7), ('call_to_action', 13)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Schrijf je titel hier', 'label': 'Titel', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Groot'), ('h3', 'Medium'), ('h4', 'Klein')], 'help_text': 'Hoe groot moet de titel zijn?', 'label': 'Grootte'}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('portfolio.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Foto', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Onderschrift', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Bron', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Titel', 'max_length': 60, 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Beschrijving', 'required': True}), 10: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Pagina link', 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'Website link', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Meer info', 'label': 'Knop tekst', 'max_length': 50, 'required': True}), 13: ('wagtail.blocks.StructBlock', [[('title', 8), ('text', 9), ('button_page', 10), ('button_url', 11), ('button_text', 12)]], {})}, verbose_name='Inhoud'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Jouw foto'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Welkom tekst'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Bedankt bericht'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Achtergrond foto'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Ondertitel onder de hoofd titel', max_length=200, verbose_name='Ondertitel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Welkom op mijn portfolio', help_text='Hoofd titel op de homepage', max_length=100, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='projectindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Korte tekst over je projecten', verbose_name='Beschrijving'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 7), ('call_to_action', 13), ('two_columns', 17)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Schrijf je titel hier', 'label': 'Titel', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Groot'), ('h3', 'Medium'), ('h4', 'Klein')], 'help_text': 'Hoe groot moet de titel zijn?', 'label': 'Grootte'}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('portfolio.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Foto', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Onderschrift', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Bron', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Titel', 'max_length': 60, 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Beschrijving', 'required': True}), 10: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Pagina link', 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'Website link', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Meer info', 'label': 'Knop tekst', 'max_length': 50, 'required': True}), 13: ('wagtail.blocks.StructBlock', [[('title', 8), ('text', 9), ('button_page', 10), ('button_url', 11), ('button_text', 12)]], {}), 14: ('wagtail.blocks.RichTextBlock', (), {}), 15: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 14), ('image', 7)]], {'icon': 'arrow-left', 'label': 'Linker kant'}), 16: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 14), ('image', 7)]], {'icon': 'arrow-right', 'label': 'Rechter kant'}), 17: ('wagtail.blocks.StructBlock', [[('left_column', 15), ('right_column', 16)]], {})}, verbose_name='Inhoud'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hoofd foto'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link naar GitHub', verbose_name='GitHub link'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='intro',
            field=models.TextField(help_text='Korte beschrijving van het project', max_length=500, verbose_name='Samenvatting'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='live_url',
            field=models.URLField(blank=True, help_text='Link naar live website', verbose_name='Live link'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='technologies',
            field=models.ManyToManyField(blank=True, help_text='Welke technologieën heb je gebruikt?', to='portfolio.technology', verbose_name='Gebruikte technologieën'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icoon'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Naam'),
        ),
    ]
