# Generated by Django 5.2.10 on 2026-01-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_aboutpage_options_alter_contactpage_options_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='projectindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='icon',
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='CTA link naar pagina'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='CTA tekst'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_url',
            field=models.URLField(blank=True, verbose_name='CTA externe URL'),
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='ProjectIndexPage',
        ),
        migrations.DeleteModel(
            name='ProjectPage',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
