# Generated by Django 5.2.10 on 2026-01-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectindexpage_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(blank=True, help_text='Je e-mailadres', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Link naar je LinkedIn profiel', verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Je telefoonnummer', max_length=50, verbose_name='Telefoonnummer'),
        ),
    ]
