# Generated by Django 5.2.10 on 2026-01-16 09:01

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_homepage_email_homepage_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_projects_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Welkom op mijn portfolio', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='ProjectIndexPage',
        ),
        migrations.DeleteModel(
            name='ProjectPage',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
