# Generated by Django 5.2.10 on 2026-01-16 09:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_projectpage_featured_image_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_projects_title',
            field=models.CharField(default='Uitgelichte projecten', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name_plural': 'Technologieën',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('project_date', models.DateField(blank=True, null=True)),
                ('intro', models.TextField(max_length=500)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 7), ('call_to_action', 12), ('two_columns', 16)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Schrijf je titel hier', 'label': 'Titel', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Groot'), ('h3', 'Medium'), ('h4', 'Klein')], 'help_text': 'Hoe groot moet de titel zijn?', 'label': 'Grootte'}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('portfolio.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Foto', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Onderschrift', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Bron', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titel van de CTA', 'required': True}), 9: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Kies een interne pagina', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Of externe URL', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Lees meer', 'help_text': 'Tekst op de knop'}), 12: ('wagtail.blocks.StructBlock', [[('title', 8), ('page', 9), ('url', 10), ('button_text', 11)]], {}), 13: ('wagtail.blocks.RichTextBlock', (), {}), 14: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 13), ('image', 7)]], {'icon': 'arrow-left', 'label': 'Linker kant'}), 15: ('wagtail.blocks.StreamBlock', [[('heading', 2), ('paragraph', 13), ('image', 7)]], {'icon': 'arrow-right', 'label': 'Rechter kant'}), 16: ('wagtail.blocks.StructBlock', [[('left_column', 14), ('right_column', 15)]], {})})),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('technologies', models.ManyToManyField(blank=True, to='portfolio.technology')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
